### PR TITLE
Training Model in QA

### PR DESCRIPTION
**Pull request by atul5001**
## Training the Model in QA.

Models List to train:
1. https://github.com/atul5001/CV-PdM-RE-Evaluation/blob/main/data/CV-PdM-RE_Pernis_models_ready_QA_model_ids.csv 
2. https://github.com/atul5001/CV-PdM-RE-Evaluation/blob/main/data/CV-PdM-RE_Non_Pernis_models_ready_QA_model_ids.csv

Currently working on Model-Id: `https://shell-qa-controlvalves-prime-sso.c3iot.ai/models/97dbe40b-232a-4494-bd0d-0bf2e3fe8101/overview`

image

### CODE REVIEW

**Comment by atul5001** [comment]
If, rendering not available, please follow the screenshot:
image

**Comment by atul5001** [comment]
Training Completed:
image

Took **21 minutes to train**

**Comment by atul5001** [comment]
image

Looks like, we might have missed the type of equipment that is not set for the `predictionTarget`

**Comment by massimodossola** [comment]
> image
> 
> Looks like, we might have missed the type of equipment that is not set for the `predictionTarget`

Yes, in Prod many equipment type are empty if they are Control Valves. Better to have them populated in QA. If in Prod is null, let's put Control Valves as equipment type

**Comment by atul5001** [comment]
image

**Comment by atul5001** [comment]
@massimodossola waiting for your 🟢 signal to merge this and trigger training.

**Review by massimodossola — APPROVED** [review]
@atul5001 LGTM. Let's wait before training all the model, I want to understand if we need to load the missing data from SSIP

**Comment by atul5001** [comment]
> @atul5001 LGTM. Let's wait before training all the model, I want to understand if we need to load the missing data from SSIP

I have asked Arun to check the data for the features attached to QA models.
He should also come back with some information.

Also, would be good to have the data-points-count from RE team as well to conclude the data-check.
Thoughts everyone?

**Comment by atul5001** [comment]
Closing this as @massimodossola confirmed on the data-load gaps.

**Pull request merged**
