### PR TITLE
DeerPark Asset | Correlation + Model Training

### PR DESCRIPTION
**Pull request by atul5001**
Tasks to be completed:
- [x] Plant Level Correlation
- [x] Related-Tag level Correlation
- [x] Model Training
- [x] Saving CSV

### Correlation Completed but Correlation Values are None
image

### CODE REVIEW

**Comment by atul5001** [comment]
> Tasks to be completed:
> 
> * [ ]  Plant Level Correlation
> * [ ]  Related-Tag level Correlation
> * [ ]  Model Training
> * [ ]  Saving CSV
> 
> ### Correlation Completed but Correlation Values are None
> image

@ArunVenugopal-Shell , can you check for this Asset as well?

**Review by massimodossola — APPROVED** [review]

**Comment by atul5001** [comment]
### Correlation-Job is working now.
Scores are populated! for both the models.

Screenshot 2023-07-17 at 12 09 11 PM
Screenshot 2023-07-17 at 12 09 38 PM

Attached Features used in the PROD Models as well:
image

**Comment by atul5001** [comment]
Screenshot 2023-07-17 at 12 54 51 PM
Screenshot 2023-07-17 at 12 54 58 PM

**Comment by JianiQu** [comment]
> Screenshot 2023-07-17 at 12 54 51 PM Screenshot 2023-07-17 at 12 54 58 PM

could you clarify, avg 38 mins is the time for 1 model training? thanks

**Comment by atul5001** [comment]
> > Screenshot 2023-07-17 at 12 54 51 PM Screenshot 2023-07-17 at 12 54 58 PM
> 
> could you clarify, avg 38 mins is the time for 1 model training? thanks

Yes

**Comment by JianiQu** [comment]
> > > Screenshot 2023-07-17 at 12 54 51 PM Screenshot 2023-07-17 at 12 54 58 PM
> > 
> > 
> > could you clarify, avg 38 mins is the time for 1 model training? thanks
> 
> Yes

Thanks, do you have any idea about actual model training time in production? around 40 mins for 1 model is not short and for some assets you wrote it down the avg training time could be hours.

**Pull request merged**
